export const Top10sList: string[] = [
  "Las 10 carreras con mayor número de profesionistas.",
  "Las 10 carreras con mayor calidad de inversión en universidades privadas.",
  "Las 10 carreras con mayor calidad de inversión en universidades públicas.",
  "Las 10 carreras con el mayor porcentaje de mujeres en nuevo ingreso.",
  "Las 10 carreras con el mayor porcentaje de hombres en nuevo ingreso.",
  "Las 10 carreras más demandadas (porcentaje de aceptación en universidades públicas).",
  "Las 10 carreras con mayor porcentaje de mujeres.",
  "Las 10 carreras con mayor porcentaje de desempleados.",
  "Las 10 carreras con mayor porcentaje de informalidad.",
  "Las 10 carreras con mayor porcentaje de jóvenes.",
  "Las 10 carreras con más profesionistas con posgrado.",
  "Las 10 carreras con mayor matrícula.",
  "Las 10 carreras con mayor tasa de retorno en universidades públicas.",
  "Las 10 carreras con mayor tasa de retorno en universidades privadas.",
  "Las 10 carreras con menor tasa de retorno en universidades públicas.",
  "Las 10 carreras con menor tasa de retorno en universidades privadas.",
  "Las 10 carreras con mayor riesgo.",
  "Las 10 carreras con menor riesgo.",
  "Las 10 carreras mejor pagadas.",
  "Las 10 carreras peor pagadas."
]

export const CarrersList : string[]=[
  "Diseño curricular y pedagogía",
  "Orientación e intervención educativa",
  "Ciencias de la educación",
  "Planes multidisciplinarios o generales del campo de formación docente",
  "Formación docente en educación básica, nivel preescolar",
  "Formación docente en educación básica, nivel primaria",
  "Formación docente en educación básica, nivel secundaria",
  "Formación docente en la enseñanza de asignaturas específicas",
  "Formación docente en otros servicios educativos",
  "Bellas artes",
  "Música",
  "Diseño y comunicación gráfica y editorial",
  "Diseño industrial, de moda e interiores",
  "Adquisición de idiomas extranjeros",
  "Literatura",
  "Historia y arqueología",
  "Planes multidisciplinarios o generales del campo de ciencias sociales y estudios del comportamiento",
  "Psicología",
  "Sociología y antropología",
  "Ciencias políticas",
  "Economía",
  "Trabajo y atención social",
  "Comunicación y periodismo",
  "Derecho",
  "Criminología y criminalística",
  "Negocios y comercio",
  "Mercadotecnia y publicidad",
  "Finanzas, banca y seguros",
  "Contabilidad y fiscalización",
  "Planes multidisciplinarios o generales del campo de administración y gestión",
  "Administración de empresas",
  "Administración turística y de restaurantes",
  "Administración pública",
  "Administración en el ámbito de la ingeniería y la construcción",
  "Biología",
  "Bioquímica y biofísica",
  "Ecología y ciencias ambientales",
  "Química",
  "Matemáticas",
  "Planes multidisciplinarios o generales del campo de innovación en tecnologías de la información y la comunicación",
  "Ciencias computacionales",
  "Desarrollo de software",
  "Informática",
  "Ing. Mecánica y profesiones afines al trabajo metálico",
  "Ing. Electricidad y generación de energía",
  "Ing. Electrónica, automatización y aplicaciones de la mecánica-eléctrica",
  "Ing. de procesos químicos",
  "Ing. Vehículos, barcos y aeronaves motorizadas",
  "Ing. Tecnologías para la protección del medio ambiente",
  "Ingeniería industrial",
  "Ing. Industria de la alimentación",
  "Ing. Industria de la minería, extracción y metalurgia",
  "Arquitectura y urbanismo",
  "Construcción e ingeniería civil",
  "Producción y explotación agrícola y ganadera",
  "Veterinaria",
  "Medicina general",
  "Medicina de especialidad",
  "Enfermería general y obstetricia",
  "Estomatología y odontología general",
  "Terapia y rehabilitación",
  "Nutrición",
  "Deportes",
  "Gastronomía y servicios de alimentos",
  "Hospitalidad y turismo"
]

export const TSUList: string[] = [
  "Formación docente en educación básica, nivel preescolar",
  "Formación docente en otros servicios educativos",
  "Trabajo y atención social",
  "Contabilidad y fiscalización",
  "Planes multidisciplinarios o generales del campo de administración y gestión",
  "Desarrollo de software",
  "Planes multidisciplinarios o generales del campo de implementación de las tecnologías de la información y la comunicación",
  "Informática",
  "Ing. Mecánica y profesiones afines al trabajo metálico",
  "Ing. Electricidad y generación de energía",
  "Ing. Electrónica, automatización y aplicaciones de la mecánica-eléctrica",
  "Ing. Vehículos, barcos y aeronaves motorizadas",
  "Ing. industrial",
  "Enfermería general y obstetricia",
  "Servicios de cuidado personal y belleza",
  "Servicios de apoyo y asistencia administrativa"
]
