export type { IconProps } from "./icon.types"

export { default as MenuIcon } from "./menu.icon"
export { default as CurrencyExchangeIcon } from "./currency-exchange.icon"
export { default as CoinIcon } from "./coin.icon"
export { default as TrendingUpIcon } from "./trending-up.icon"
export { default as TrendingDownIcon } from "./trending-down.icon"
export { default as FacebookIcon } from "./facebook.icon"
export { default as XIcon } from "./x.icon"
export { default as InstagramIcon } from "./instagram.icon"
export { default as UsersIcon } from "./users.icon"
export { default as FemaleIcon } from "./female.icon"
export { default as MaleIcon } from "./male.icon"
export { default as StarIcon } from "./star.icon"
export { default as UserXIcon } from "./user-x.icon"
export { default as FileXIcon } from "./file-x.icon"
export { default as SproutIcon } from "./sprout.icon"
export { default as GraduationCapIcon } from "./graduation-cap.icon"
export { default as ClipboardListIcon } from "./clipboard-list.icon"
export { default as AlertTriangleIcon } from "./alert-triangle.icon"
export { default as ShieldCheckIcon } from "./shield-check.icon"
export { default as BanknoteIcon } from "./banknote.icon"
